### ISSUE TITLE
The L2 loss function does not use

### ISSUE THREAD

**Issue by eventhorizon7** [imperial-qore/TranAD#45]
Hi, thank you very much for your work, but I found that the loss function of the code is not consistent with the loss function in the paper, the code does not use L2 loss, why is this

**Comment by agiannoul** [comment]
Basically, I can't understand two things

1) based on the code the anomaly score depends only on O2_hat (instead of both O1 and O2_hat, as in the paper)

2) In the paper you suggest providing C and W.
But in the code, it seems that you provide the W as C, and last element as W (which maybe is fine, but I cant follow the process of thinking). 

3) I am not sure where is the calculation of O2 (of phase 1)

In general, great work, thank you!

**Comment by gucci-san** [comment]
I had the same question. Did you solve it?

**Comment by shreshthtuli** [comment]
You can see the refactored version here: https://github.com/imperial-qore/TranAD/blob/f2adcf56010e4530bc588fd63b0701b454ed7aff/main.py#L265.

**Comment by Bi2nKun** [comment]
I made the modifications according to the commit, and the results were much worse
